//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WaterForAfrica
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_EVENTS
    {
        public int EventId { get; set; }
        public string EventDescription { get; set; }
        public System.DateTime StartDate { get; set; }
        public System.DateTime EndDate { get; set; }
        public string City { get; set; }
        public string State { get; set; }
        public int LoginId { get; set; }
    
        public virtual T_LOGIN T_LOGIN { get; set; }
    }
}
