//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Events
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_LOGIN
    {
        public T_LOGIN()
        {
            this.T_PROFILE_DETAILS = new HashSet<T_PROFILE_DETAILS>();
        }
    
        public int LoginId { get; set; }
        public string UserName { get; set; }
        public string Password { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime CreatedOn { get; set; }
    
        public virtual ICollection<T_PROFILE_DETAILS> T_PROFILE_DETAILS { get; set; }
    }
}
