//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WaterForAfrica
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_PROFILE_DETAILS
    {
        public int ProfileId { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public int LoginId { get; set; }
    
        public virtual T_LOGIN T_LOGIN { get; set; }
    }
}
